//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF.Classes")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.Service.UserDTO[] FriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.Service.RoomDTO[] RoomsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.Service.UserDTO[] Friends {
            get {
                return this.FriendsField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendsField, value) != true)) {
                    this.FriendsField = value;
                    this.RaisePropertyChanged("Friends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConfirmed {
            get {
                return this.IsConfirmedField;
            }
            set {
                if ((this.IsConfirmedField.Equals(value) != true)) {
                    this.IsConfirmedField = value;
                    this.RaisePropertyChanged("IsConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.Service.RoomDTO[] Rooms {
            get {
                return this.RoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomsField, value) != true)) {
                    this.RoomsField = value;
                    this.RaisePropertyChanged("Rooms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF.Classes")]
    [System.SerializableAttribute()]
    public partial class RoomDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.Service.UserDTO[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublish {
            get {
                return this.IsPublishField;
            }
            set {
                if ((this.IsPublishField.Equals(value) != true)) {
                    this.IsPublishField = value;
                    this.RaisePropertyChanged("IsPublish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.Service.UserDTO[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF.Classes")]
    [System.SerializableAttribute()]
    public partial class MessageDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.Service.AttachDTO[] AttachesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeSendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.Service.RoomDTO RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.Service.UserDTO SenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.Service.AttachDTO[] Attaches {
            get {
                return this.AttachesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachesField, value) != true)) {
                    this.AttachesField = value;
                    this.RaisePropertyChanged("Attaches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeSended {
            get {
                return this.DateTimeSendedField;
            }
            set {
                if ((this.DateTimeSendedField.Equals(value) != true)) {
                    this.DateTimeSendedField = value;
                    this.RaisePropertyChanged("DateTimeSended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.Service.RoomDTO Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.Service.UserDTO Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachDTO", Namespace="http://schemas.datacontract.org/2004/07/WCF.Classes")]
    [System.SerializableAttribute()]
    public partial class AttachDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPF.Service.MessageDTO MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPF.Service.MessageDTO Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IUser", CallbackContract=typeof(WPF.Service.IUserCallback))]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/SignIn", ReplyAction="http://tempuri.org/IUser/SignInResponse")]
        WPF.Service.UserDTO SignIn(string EmailOrLogin, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/SignIn", ReplyAction="http://tempuri.org/IUser/SignInResponse")]
        System.Threading.Tasks.Task<WPF.Service.UserDTO> SignInAsync(string EmailOrLogin, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Registration", ReplyAction="http://tempuri.org/IUser/RegistrationResponse")]
        WPF.Service.UserDTO Registration(string Email, string Name, string Password, string Login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Registration", ReplyAction="http://tempuri.org/IUser/RegistrationResponse")]
        System.Threading.Tasks.Task<WPF.Service.UserDTO> RegistrationAsync(string Email, string Name, string Password, string Login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Confirming", ReplyAction="http://tempuri.org/IUser/ConfirmingResponse")]
        bool Confirming(int user_id, int Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Confirming", ReplyAction="http://tempuri.org/IUser/ConfirmingResponse")]
        System.Threading.Tasks.Task<bool> ConfirmingAsync(int user_id, int Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ResendCode", ReplyAction="http://tempuri.org/IUser/ResendCodeResponse")]
        bool ResendCode(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ResendCode", ReplyAction="http://tempuri.org/IUser/ResendCodeResponse")]
        System.Threading.Tasks.Task<bool> ResendCodeAsync(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/getSearchPeople", ReplyAction="http://tempuri.org/IUser/getSearchPeopleResponse")]
        WPF.Service.UserDTO[] getSearchPeople(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/getSearchPeople", ReplyAction="http://tempuri.org/IUser/getSearchPeopleResponse")]
        System.Threading.Tasks.Task<WPF.Service.UserDTO[]> getSearchPeopleAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Add_Friend", ReplyAction="http://tempuri.org/IUser/Add_FriendResponse")]
        void Add_Friend(int your_id, int friend_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Add_Friend", ReplyAction="http://tempuri.org/IUser/Add_FriendResponse")]
        System.Threading.Tasks.Task Add_FriendAsync(int your_id, int friend_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/RemoveFriend", ReplyAction="http://tempuri.org/IUser/RemoveFriendResponse")]
        void RemoveFriend(int your_id, int friend_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/RemoveFriend", ReplyAction="http://tempuri.org/IUser/RemoveFriendResponse")]
        System.Threading.Tasks.Task RemoveFriendAsync(int your_id, int friend_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserId", ReplyAction="http://tempuri.org/IUser/GetUserIdResponse")]
        WPF.Service.UserDTO GetUserId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserId", ReplyAction="http://tempuri.org/IUser/GetUserIdResponse")]
        System.Threading.Tasks.Task<WPF.Service.UserDTO> GetUserIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetFriends", ReplyAction="http://tempuri.org/IUser/GetFriendsResponse")]
        WPF.Service.UserDTO[] GetFriends(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetFriends", ReplyAction="http://tempuri.org/IUser/GetFriendsResponse")]
        System.Threading.Tasks.Task<WPF.Service.UserDTO[]> GetFriendsAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUser/GetMessage")]
        void GetMessage(WPF.Service.MessageDTO msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : WPF.Service.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.DuplexClientBase<WPF.Service.IUser>, WPF.Service.IUser {
        
        public UserClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UserClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UserClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public WPF.Service.UserDTO SignIn(string EmailOrLogin, string password) {
            return base.Channel.SignIn(EmailOrLogin, password);
        }
        
        public System.Threading.Tasks.Task<WPF.Service.UserDTO> SignInAsync(string EmailOrLogin, string password) {
            return base.Channel.SignInAsync(EmailOrLogin, password);
        }
        
        public WPF.Service.UserDTO Registration(string Email, string Name, string Password, string Login) {
            return base.Channel.Registration(Email, Name, Password, Login);
        }
        
        public System.Threading.Tasks.Task<WPF.Service.UserDTO> RegistrationAsync(string Email, string Name, string Password, string Login) {
            return base.Channel.RegistrationAsync(Email, Name, Password, Login);
        }
        
        public bool Confirming(int user_id, int Code) {
            return base.Channel.Confirming(user_id, Code);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmingAsync(int user_id, int Code) {
            return base.Channel.ConfirmingAsync(user_id, Code);
        }
        
        public bool ResendCode(int user_id) {
            return base.Channel.ResendCode(user_id);
        }
        
        public System.Threading.Tasks.Task<bool> ResendCodeAsync(int user_id) {
            return base.Channel.ResendCodeAsync(user_id);
        }
        
        public WPF.Service.UserDTO[] getSearchPeople(string Name) {
            return base.Channel.getSearchPeople(Name);
        }
        
        public System.Threading.Tasks.Task<WPF.Service.UserDTO[]> getSearchPeopleAsync(string Name) {
            return base.Channel.getSearchPeopleAsync(Name);
        }
        
        public void Add_Friend(int your_id, int friend_id) {
            base.Channel.Add_Friend(your_id, friend_id);
        }
        
        public System.Threading.Tasks.Task Add_FriendAsync(int your_id, int friend_id) {
            return base.Channel.Add_FriendAsync(your_id, friend_id);
        }
        
        public void RemoveFriend(int your_id, int friend_id) {
            base.Channel.RemoveFriend(your_id, friend_id);
        }
        
        public System.Threading.Tasks.Task RemoveFriendAsync(int your_id, int friend_id) {
            return base.Channel.RemoveFriendAsync(your_id, friend_id);
        }
        
        public WPF.Service.UserDTO GetUserId(int id) {
            return base.Channel.GetUserId(id);
        }
        
        public System.Threading.Tasks.Task<WPF.Service.UserDTO> GetUserIdAsync(int id) {
            return base.Channel.GetUserIdAsync(id);
        }
        
        public WPF.Service.UserDTO[] GetFriends(int id) {
            return base.Channel.GetFriends(id);
        }
        
        public System.Threading.Tasks.Task<WPF.Service.UserDTO[]> GetFriendsAsync(int id) {
            return base.Channel.GetFriendsAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IMessage", CallbackContract=typeof(WPF.Service.IMessageCallback))]
    public interface IMessage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessage/SendMessage", ReplyAction="http://tempuri.org/IMessage/SendMessageResponse")]
        void SendMessage(string body, WPF.Service.RoomDTO room, WPF.Service.UserDTO sender, WPF.Service.AttachDTO attach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessage/SendMessage", ReplyAction="http://tempuri.org/IMessage/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string body, WPF.Service.RoomDTO room, WPF.Service.UserDTO sender, WPF.Service.AttachDTO attach);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessage/GetMessage")]
        void GetMessage(WPF.Service.MessageDTO msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageChannel : WPF.Service.IMessage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageClient : System.ServiceModel.DuplexClientBase<WPF.Service.IMessage>, WPF.Service.IMessage {
        
        public MessageClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MessageClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MessageClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MessageClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MessageClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendMessage(string body, WPF.Service.RoomDTO room, WPF.Service.UserDTO sender, WPF.Service.AttachDTO attach) {
            base.Channel.SendMessage(body, room, sender, attach);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string body, WPF.Service.RoomDTO room, WPF.Service.UserDTO sender, WPF.Service.AttachDTO attach) {
            return base.Channel.SendMessageAsync(body, room, sender, attach);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IRoom", CallbackContract=typeof(WPF.Service.IRoomCallback))]
    public interface IRoom {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/CreateRoom", ReplyAction="http://tempuri.org/IRoom/CreateRoomResponse")]
        void CreateRoom(WPF.Service.RoomDTO room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/CreateRoom", ReplyAction="http://tempuri.org/IRoom/CreateRoomResponse")]
        System.Threading.Tasks.Task CreateRoomAsync(WPF.Service.RoomDTO room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/SendMessageAllUsersInRoom", ReplyAction="http://tempuri.org/IRoom/SendMessageAllUsersInRoomResponse")]
        void SendMessageAllUsersInRoom(WPF.Service.RoomDTO room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/SendMessageAllUsersInRoom", ReplyAction="http://tempuri.org/IRoom/SendMessageAllUsersInRoomResponse")]
        System.Threading.Tasks.Task SendMessageAllUsersInRoomAsync(WPF.Service.RoomDTO room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/ExitFromRoom", ReplyAction="http://tempuri.org/IRoom/ExitFromRoomResponse")]
        void ExitFromRoom(int your_id, int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/ExitFromRoom", ReplyAction="http://tempuri.org/IRoom/ExitFromRoomResponse")]
        System.Threading.Tasks.Task ExitFromRoomAsync(int your_id, int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/JoinInRoom", ReplyAction="http://tempuri.org/IRoom/JoinInRoomResponse")]
        void JoinInRoom(int your_id, int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/JoinInRoom", ReplyAction="http://tempuri.org/IRoom/JoinInRoomResponse")]
        System.Threading.Tasks.Task JoinInRoomAsync(int your_id, int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/GetRooms", ReplyAction="http://tempuri.org/IRoom/GetRoomsResponse")]
        WPF.Service.RoomDTO[] GetRooms(int your_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/GetRooms", ReplyAction="http://tempuri.org/IRoom/GetRoomsResponse")]
        System.Threading.Tasks.Task<WPF.Service.RoomDTO[]> GetRoomsAsync(int your_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoom/GetMessage")]
        void GetMessage(WPF.Service.MessageDTO msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomChannel : WPF.Service.IRoom, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomClient : System.ServiceModel.DuplexClientBase<WPF.Service.IRoom>, WPF.Service.IRoom {
        
        public RoomClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RoomClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RoomClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RoomClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RoomClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void CreateRoom(WPF.Service.RoomDTO room) {
            base.Channel.CreateRoom(room);
        }
        
        public System.Threading.Tasks.Task CreateRoomAsync(WPF.Service.RoomDTO room) {
            return base.Channel.CreateRoomAsync(room);
        }
        
        public void SendMessageAllUsersInRoom(WPF.Service.RoomDTO room) {
            base.Channel.SendMessageAllUsersInRoom(room);
        }
        
        public System.Threading.Tasks.Task SendMessageAllUsersInRoomAsync(WPF.Service.RoomDTO room) {
            return base.Channel.SendMessageAllUsersInRoomAsync(room);
        }
        
        public void ExitFromRoom(int your_id, int room_id) {
            base.Channel.ExitFromRoom(your_id, room_id);
        }
        
        public System.Threading.Tasks.Task ExitFromRoomAsync(int your_id, int room_id) {
            return base.Channel.ExitFromRoomAsync(your_id, room_id);
        }
        
        public void JoinInRoom(int your_id, int room_id) {
            base.Channel.JoinInRoom(your_id, room_id);
        }
        
        public System.Threading.Tasks.Task JoinInRoomAsync(int your_id, int room_id) {
            return base.Channel.JoinInRoomAsync(your_id, room_id);
        }
        
        public WPF.Service.RoomDTO[] GetRooms(int your_id) {
            return base.Channel.GetRooms(your_id);
        }
        
        public System.Threading.Tasks.Task<WPF.Service.RoomDTO[]> GetRoomsAsync(int your_id) {
            return base.Channel.GetRoomsAsync(your_id);
        }
    }
}
